apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: "{{ .values.image.repository }}:{{ .values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: url-shortener-secrets
            - configMapRef:
                name: url-shortener-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .values.profile }}"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "{{ .values.resources.requests.cpu }}"
              memory: "{{ .values.resources.requests.memory }}"
            limits:
              cpu: "{{ .values.resources.limits.cpu }}"
              memory: "{{ .values.resources.limits.memory }}"
          readinessGates: []
      imagePullSecrets:
        - name: "{{ .values.image.pullSecret | default "registry-secret" }}"
