apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://postgres.example.svc.cluster.local:5432/url_shortener
  DB_USER: urlshortener
  DB_PASSWORD: "YOUR_DB_PASSWORD_HERE"
  URL_SHORTENER_API_URL: https://api.external-shortener.example
  URL_SHORTENER_API_KEY: "YOUR_PROVIDER_KEY"
  REDIS_HOST: redis-master
  REDIS_PORT: "6379"